name: ppg_paper_gpu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.12
  - pip=23.1.2
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - torch==2.0.1+cu117
    - torchvision==0.15.2+cu117
    - scipy==1.11.1
    - transformers==4.31.0
    - scikit-learn==1.3.0
    - hydra-core==1.3.2
    - timm==0.9.7
    - matplotlib==3.7.2
    - pandas==2.1.1
    - openpyxl==3.1.2
    - faiss-cpu==1.7.4

    # For development
    - ipykernel==6.24.0
    - ipywidgets==8.0.7
    - pre-commit==3.3.3
    - black==23.7.0
    - isort==5.12.0
    - flake8==6.1.0
